# Generated by Django 4.0.7 on 2022-09-23 16:59

from django.db import migrations, models
import product.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', product.fields.ThumbnailImageField(upload_to='photo/%Y/%m')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='UploadDate')),
            ],
            options={
                'ordering': ('upload_dt',),
            },
        ),
    ]
